export const largeProducts = [
  {
    "id": "local_p_1",
    "name": "Biba Casual Shirts",
    "slug": "biba-casual-shirts-2",
    "price": 1044,
    "originalPrice": 1800,
    "discountPercentage": 42,
    "category": "Men",
    "brand": "Biba",
    "color": "Blue",
    "type": "Casual Shirts",
    "rating": 4.5,
    "review_count": 299,
    "images": ["/images/men/clothing/casual-shirts/shirt1.webp"],
    "image": "/images/men/clothing/casual-shirts/shirt1.webp",
    "description": "Premium linen shirt for ultimate comfort.",
    "sizes": ["S", "M", "L", "XL"],
    "stock": 12,
    "featured": true
  },
  {
    "id": "local_p_2",
    "name": "Allen Solly Casual Shirts",
    "slug": "allen-solly-casual-shirts-3",
    "price": 3153,
    "originalPrice": 3710,
    "discountPercentage": 15,
    "category": "Men",
    "brand": "Allen Solly",
    "color": "Beige",
    "type": "Casual Shirts",
    "rating": 4.8,
    "review_count": 27,
    "images": ["/images/men/clothing/casual-shirts/shirt10.webp"],
    "image": "/images/men/clothing/casual-shirts/shirt10.webp",
    "description": "Elegant beige shirt with a perfect fit.",
    "sizes": ["M", "L", "XL"],
    "stock": 15,
    "featured": true
  },
  {
    "id": "local_p_3",
    "name": "Biba Casual Shirts",
    "slug": "biba-casual-shirts-4",
    "price": 1251,
    "originalPrice": 1840,
    "discountPercentage": 32,
    "category": "Men",
    "brand": "Biba",
    "color": "White",
    "type": "Casual Shirts",
    "rating": 4.6,
    "review_count": 276,
    "images": ["/images/men/clothing/casual-shirts/shirt2.webp"],
    "description": "Premium cotton shirt for a classic look.",
    "sizes": ["S", "M", "L", "XL"],
    "stock": 5,
    "isLimitedStock": true
  },
  {
    "id": "local_p_4",
    "name": "Zara Casual Shirts",
    "slug": "zara-casual-shirts-5",
    "price": 750,
    "originalPrice": 1250,
    "discountPercentage": 40,
    "category": "Men",
    "brand": "Zara",
    "color": "Black",
    "type": "Casual Shirts",
    "rating": 4.7,
    "review_count": 418,
    "images": ["/images/men/clothing/casual-shirts/shirt3.webp"],
    "description": "Modern black shirt for any occasion.",
    "sizes": ["M", "L", "XL"],
    "stock": 10,
    "featured": true
  },
  {
    "id": "local_p_5",
    "name": "Zara Casual Shirts",
    "slug": "zara-casual-shirts-6",
    "price": 2649,
    "originalPrice": 2880,
    "discountPercentage": 8,
    "category": "Men",
    "brand": "Zara",
    "color": "Green",
    "type": "Casual Shirts",
    "rating": 4.9,
    "review_count": 68,
    "images": ["/images/men/clothing/casual-shirts/shirt4.webp"],
    "description": "Premium casual shirt for daily wear.",
    "sizes": ["S", "M", "L"],
    "stock": 14,
    "bestseller": true
  },
  {
    "id": "local_p_6",
    "name": "Puma Casual Shirts",
    "slug": "puma-casual-shirts-7",
    "price": 3312,
    "originalPrice": 4040,
    "discountPercentage": 18,
    "category": "Men",
    "brand": "Puma",
    "color": "White",
    "type": "Casual Shirts",
    "rating": 4.7,
    "review_count": 473,
    "images": ["/images/men/clothing/casual-shirts/shirt5.webp"],
    "description": "Stylish and comfortable casual shirt.",
    "sizes": ["S", "M", "L"],
    "stock": 3,
    "isLimitedStock": true,
    "new_arrival": true
  },
  {
    "id": "local_p_7",
    "name": "W for Woman Formal",
    "slug": "w-woman-formal-1",
    "price": 3723,
    "originalPrice": 4280,
    "discountPercentage": 13,
    "category": "Men",
    "brand": "W for Woman",
    "color": "Beige",
    "type": "Formal Shirts",
    "rating": 4.6,
    "review_count": 182,
    "images": ["/images/men/clothing/formal-shirts/fshirt6.webp"],
    "description": "Elegant formal shirt for men.",
    "sizes": ["S", "M", "L"],
    "stock": 9,
    "featured": true
  },
  {
    "id": "local_p_8",
    "name": "Levis Casual Shirts",
    "slug": "levis-casual-shirts-9",
    "price": 2625,
    "originalPrice": 2950,
    "discountPercentage": 11,
    "category": "Men",
    "brand": "Levis",
    "color": "Light Blue",
    "type": "Casual Shirts",
    "rating": 4.8,
    "review_count": 481,
    "images": ["/images/men/clothing/casual-shirts/shirt7.webp"],
    "description": "Classic casual shirt from Levis.",
    "sizes": ["S", "M", "L", "XL"],
    "stock": 7,
    "bestseller": true
  },
  {
    "id": "local_p_9",
    "name": "Puma Casual Shirts",
    "slug": "puma-casual-shirts-10",
    "price": 1845,
    "originalPrice": 2500,
    "discountPercentage": 26,
    "category": "Men",
    "brand": "Puma",
    "color": "White",
    "type": "Casual Shirts",
    "rating": 4.9,
    "review_count": 207,
    "images": ["/images/men/clothing/casual-shirts/shirt8.webp"],
    "description": "Clean white casual shirt for any event.",
    "sizes": ["XS", "S", "M"],
    "stock": 13,
    "featured": true
  },
  {
    "id": "local_p_10",
    "name": "W for Woman Casual",
    "slug": "w-woman-casual-1",
    "price": 1656,
    "originalPrice": 2670,
    "discountPercentage": 38,
    "category": "Men",
    "brand": "W for Woman",
    "color": "Red",
    "type": "Casual Shirts",
    "rating": 4.5,
    "review_count": 100,
    "images": ["/images/men/clothing/casual-shirts/shirt9.webp"],
    "description": "Stylish red casual shirt.",
    "sizes": ["M", "L", "XL"],
    "stock": 2,
    "isLimitedStock": true,
    "new_arrival": true
  },
  {
    "id": "local_p_11",
    "name": "Zara Formal Shirts",
    "slug": "zara-formal-1",
    "price": 4331,
    "originalPrice": 5680,
    "discountPercentage": 23,
    "category": "Men",
    "brand": "Zara",
    "color": "Navy",
    "type": "Formal Shirts",
    "rating": 5.0,
    "review_count": 48,
    "images": ["/images/men/clothing/formal-shirts/fshirt1.webp"],
    "description": "Luxurious formal shirt for special events.",
    "sizes": ["XS", "S", "M", "L"],
    "stock": 5,
    "featured": true
  },
  {
    "id": "local_p_12",
    "name": "Biba Formal Shirts",
    "slug": "biba-formal-2",
    "price": 718,
    "originalPrice": 790,
    "discountPercentage": 9,
    "category": "Men",
    "brand": "Biba",
    "color": "Green",
    "type": "Formal Shirts",
    "rating": 4.7,
    "review_count": 187,
    "images": ["/images/men/clothing/formal-shirts/fshirt10.webp"],
    "description": "Premium formal shirt.",
    "sizes": ["S", "M", "L"],
    "stock": 15,
    "featured": false
  },
  {
    "id": "local_p_13",
    "name": "FabIndia Formal",
    "slug": "fabindia-formal-1",
    "price": 3408,
    "originalPrice": 4010,
    "discountPercentage": 15,
    "category": "Men",
    "brand": "FabIndia",
    "color": "Maroon",
    "type": "Formal Shirts",
    "rating": 4.8,
    "review_count": 420,
    "images": ["/images/men/clothing/formal-shirts/fshirt2.webp"],
    "description": "High-quality ethnic formal wear.",
    "sizes": ["M", "L", "XL"],
    "stock": 6,
    "featured": true
  },
  {
    "id": "local_p_14",
    "name": "Allen Solly Formal",
    "slug": "allen-solly-formal-1",
    "price": 1166,
    "originalPrice": 2120,
    "discountPercentage": 45,
    "category": "Men",
    "brand": "Allen Solly",
    "color": "Beige",
    "type": "Formal Shirts",
    "rating": 3.7,
    "review_count": 321,
    "images": ["/images/men/clothing/formal-shirts/fshirt3.webp"],
    "description": "Sharp formal shirt for work.",
    "sizes": ["S", "M", "L"],
    "stock": 7,
    "bestseller": true
  },
  {
    "id": "local_p_15",
    "name": "Puma Formal Shirts",
    "slug": "puma-formal-1",
    "price": 1146,
    "originalPrice": 1910,
    "discountPercentage": 40,
    "category": "Men",
    "brand": "Puma",
    "color": "Black",
    "type": "Formal Shirts",
    "rating": 5.0,
    "review_count": 450,
    "images": ["/images/men/clothing/formal-shirts/fshirt4.webp"],
    "description": "Clean black formal shirt.",
    "sizes": ["S", "M", "L"],
    "stock": 3,
    "isLimitedStock": true
  },
  {
    "id": "local_p_16",
    "name": "H&M Formal Shirts",
    "slug": "hm-formal-1",
    "price": 808,
    "originalPrice": 940,
    "discountPercentage": 14,
    "category": "Men",
    "brand": "H&M",
    "color": "Navy",
    "type": "Formal Shirts",
    "rating": 4.8,
    "review_count": 216,
    "images": ["/images/men/clothing/formal-shirts/fshirt5.webp"],
    "description": "Modern fit formal shirt.",
    "sizes": ["S", "M", "L"],
    "stock": 11,
    "featured": false
  },
  {
    "id": "local_p_17",
    "name": "Zara Jeans",
    "slug": "zara-jeans-1",
    "price": 2499,
    "originalPrice": 3500,
    "discountPercentage": 28,
    "category": "Men",
    "brand": "Zara",
    "color": "Blue",
    "type": "Jeans",
    "rating": 4.4,
    "review_count": 133,
    "images": ["/images/men/clothing/jeans/jeans1.webp"],
    "description": "Stylish slim fit jeans.",
    "sizes": ["30", "32", "34"],
    "stock": 12,
    "featured": true
  },
  {
    "id": "local_p_18",
    "name": "Levis 511 Slim",
    "slug": "levis-511-slim",
    "price": 3999,
    "originalPrice": 4500,
    "discountPercentage": 11,
    "category": "Men",
    "brand": "Levis",
    "color": "Dark Blue",
    "type": "Jeans",
    "rating": 4.8,
    "review_count": 850,
    "images": ["/images/men/clothing/jeans/jeans10.webp"],
    "description": "The classic 511 slim fit.",
    "sizes": ["30", "32", "34", "36"],
    "stock": 25,
    "bestseller": true
  },
  {
    "id": "local_p_19",
    "name": "Puma Sport T-Shirt",
    "slug": "puma-sport-tshirt",
    "price": 1299,
    "originalPrice": 1999,
    "discountPercentage": 35,
    "category": "Men",
    "brand": "Puma",
    "color": "Grey",
    "type": "T-Shirts",
    "rating": 4.7,
    "review_count": 120,
    "images": ["/images/men/clothing/tshirts/tshirts1.webp"],
    "description": "Breathable sport T-shirt.",
    "sizes": ["S", "M", "L", "XL"],
    "stock": 15,
    "new_arrival": true
  },
  {
    "id": "local_p_20",
    "name": "Nike Track Pants",
    "slug": "nike-track-pants",
    "price": 2499,
    "originalPrice": 2999,
    "discountPercentage": 16,
    "category": "Men",
    "brand": "Nike",
    "color": "Black",
    "type": "Track Pants",
    "rating": 4.9,
    "review_count": 360,
    "images": ["/images/men/clothing/track-pants/tpants1.webp"],
    "description": "Comfortable track pants for workouts.",
    "sizes": ["M", "L", "XL"],
    "stock": 9,
    "featured": true
  },
  {
    "id": "local_p_21",
    "name": "Biba Jeans",
    "slug": "biba-jeans-22",
    "price": 621,
    "originalPrice": 1130,
    "discount_price": 621,
    "discount": 45,
    "discountPercentage": 45,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Biba",
    "color": "Grey",
    "fabric": "Chiffon",
    "type": "Jeans",
    "pattern": "Solid",
    "fit": "Slim Fit",
    "occasion": "Festive",
    "collar": null,
    "rating": 4.3,
    "review_count": 219,
    "images": [
      "/images/men/clothing/jeans/jeans1.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans1.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34"
    ],
    "size": "28",
    "stock": 6,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_22",
    "name": "Biba Jeans",
    "slug": "biba-jeans-23",
    "price": 1966,
    "originalPrice": 3390,
    "discount_price": 1966,
    "discount": 42,
    "discountPercentage": 42,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Biba",
    "color": "Teal",
    "fabric": "Nylon",
    "type": "Jeans",
    "pattern": "Striped",
    "fit": "Relaxed Fit",
    "occasion": "Formal",
    "collar": null,
    "rating": 4.4,
    "review_count": 168,
    "images": [
      "/images/men/clothing/jeans/jeans10.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans10.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34"
    ],
    "size": "28",
    "stock": 11,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_23",
    "name": "Zara Jeans",
    "slug": "zara-jeans-24",
    "price": 2986,
    "originalPrice": 4740,
    "discount_price": 2986,
    "discount": 37,
    "discountPercentage": 37,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Zara",
    "color": "Grey",
    "fabric": "Leather",
    "type": "Jeans",
    "pattern": "Floral",
    "fit": "Tailored Fit",
    "occasion": "Casual",
    "collar": null,
    "rating": 3.7,
    "review_count": 392,
    "images": [
      "/images/men/clothing/jeans/jeans2.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans2.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36"
    ],
    "size": "28",
    "stock": 0,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_24",
    "name": "Biba Jeans",
    "slug": "biba-jeans-25",
    "price": 1611,
    "originalPrice": 1990,
    "discount_price": 1611,
    "discount": 19,
    "discountPercentage": 19,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Biba",
    "color": "White",
    "fabric": "Silk",
    "type": "Jeans",
    "pattern": "Solid",
    "fit": "Relaxed Fit",
    "occasion": "Lounge",
    "collar": null,
    "rating": 3.7,
    "review_count": 19,
    "images": [
      "/images/men/clothing/jeans/jeans3.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans3.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38"
    ],
    "size": "28",
    "stock": 13,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_25",
    "name": "Sabyasachi Jeans",
    "slug": "sabyasachi-jeans-26",
    "price": 2172,
    "originalPrice": 3620,
    "discount_price": 2172,
    "discount": 40,
    "discountPercentage": 40,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Sabyasachi",
    "color": "Yellow",
    "fabric": "Georgette",
    "type": "Jeans",
    "pattern": "Solid",
    "fit": "Slim Fit",
    "occasion": "Party",
    "collar": null,
    "rating": 4.2,
    "review_count": 110,
    "images": [
      "/images/men/clothing/jeans/jeans4.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans4.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32"
    ],
    "size": "28",
    "stock": 13,
    "isLimitedStock": false,
    "featured": true,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_26",
    "name": "Sabyasachi Jeans",
    "slug": "sabyasachi-jeans-27",
    "price": 2729,
    "originalPrice": 3370,
    "discount_price": 2729,
    "discount": 19,
    "discountPercentage": 19,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Sabyasachi",
    "color": "Beige",
    "fabric": "Rayon",
    "type": "Jeans",
    "pattern": "Checked",
    "fit": "Skinny Fit",
    "occasion": "Formal",
    "collar": null,
    "rating": 4.8,
    "review_count": 293,
    "images": [
      "/images/men/clothing/jeans/jeans5.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans5.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32"
    ],
    "size": "28",
    "stock": 10,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_27",
    "name": "Puma Jeans",
    "slug": "puma-jeans-28",
    "price": 2183,
    "originalPrice": 3830,
    "discount_price": 2183,
    "discount": 43,
    "discountPercentage": 43,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Puma",
    "color": "White",
    "fabric": "Leather",
    "type": "Jeans",
    "pattern": "Printed",
    "fit": "Oversized",
    "occasion": "Formal",
    "collar": null,
    "rating": 4.2,
    "review_count": 361,
    "images": [
      "/images/men/clothing/jeans/jeans6.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans6.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 1,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_28",
    "name": "Sabyasachi Jeans",
    "slug": "sabyasachi-jeans-29",
    "price": 1270,
    "originalPrice": 1790,
    "discount_price": 1270,
    "discount": 29,
    "discountPercentage": 29,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Sabyasachi",
    "color": "Pink",
    "fabric": "Satin",
    "type": "Jeans",
    "pattern": "Striped",
    "fit": "Tailored Fit",
    "occasion": "Work",
    "collar": null,
    "rating": 4.8,
    "review_count": 360,
    "images": [
      "/images/men/clothing/jeans/jeans7.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans7.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 0,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": true
  },
  {
    "id": "local_p_29",
    "name": "Biba Jeans",
    "slug": "biba-jeans-30",
    "price": 4240,
    "originalPrice": 4240,
    "discount_price": 4240,
    "discount": 0,
    "discountPercentage": 0,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Biba",
    "color": "Navy",
    "fabric": "Leather",
    "type": "Jeans",
    "pattern": "Plaid",
    "fit": "Regular Fit",
    "occasion": "Festive",
    "collar": null,
    "rating": 4.5,
    "review_count": 432,
    "images": [
      "/images/men/clothing/jeans/jeans8.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans8.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34"
    ],
    "size": "28",
    "stock": 2,
    "isLimitedStock": true,
    "featured": true,
    "bestseller": false,
    "new_arrival": true
  },
  {
    "id": "local_p_30",
    "name": "Allen Solly Jeans",
    "slug": "allen-solly-jeans-31",
    "price": 1374,
    "originalPrice": 2370,
    "discount_price": 1374,
    "discount": 42,
    "discountPercentage": 42,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Allen Solly",
    "color": "Beige",
    "fabric": "Georgette",
    "type": "Jeans",
    "pattern": "Striped",
    "fit": "Slim Fit",
    "occasion": "Party",
    "collar": null,
    "rating": 3.9,
    "review_count": 355,
    "images": [
      "/images/men/clothing/jeans/jeans9.webp"
    ],
    "image": "/images/men/clothing/jeans/jeans9.webp",
    "description": "A premium jeans designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38"
    ],
    "size": "28",
    "stock": 5,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_31",
    "name": "Levis Shorts",
    "slug": "levis-shorts-32",
    "price": 2015,
    "originalPrice": 3250,
    "discount_price": 2015,
    "discount": 38,
    "discountPercentage": 38,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Levis",
    "color": "Teal",
    "fabric": "Nylon",
    "type": "Shorts",
    "pattern": "Abstract",
    "fit": "Oversized",
    "occasion": "Formal",
    "collar": null,
    "rating": 4.5,
    "review_count": 41,
    "images": [
      "/images/men/clothing/shorts/shorts1.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts1.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34"
    ],
    "size": "28",
    "stock": 8,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": true
  },
  {
    "id": "local_p_32",
    "name": "Raymond Shorts",
    "slug": "raymond-shorts-33",
    "price": 1283,
    "originalPrice": 1380,
    "discount_price": 1283,
    "discount": 7,
    "discountPercentage": 7,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Raymond",
    "color": "Red",
    "fabric": "Nylon",
    "type": "Shorts",
    "pattern": "Embroidered",
    "fit": "Oversized",
    "occasion": "Party",
    "collar": null,
    "rating": 4,
    "review_count": 310,
    "images": [
      "/images/men/clothing/shorts/shorts10.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts10.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34"
    ],
    "size": "28",
    "stock": 8,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_33",
    "name": "Puma Shorts",
    "slug": "puma-shorts-34",
    "price": 2948,
    "originalPrice": 3880,
    "discount_price": 2948,
    "discount": 24,
    "discountPercentage": 24,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Puma",
    "color": "Yellow",
    "fabric": "Leather",
    "type": "Shorts",
    "pattern": "Polka Dots",
    "fit": "Relaxed Fit",
    "occasion": "Work",
    "collar": null,
    "rating": 4.3,
    "review_count": 76,
    "images": [
      "/images/men/clothing/shorts/shorts2.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts2.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32"
    ],
    "size": "28",
    "stock": 9,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_34",
    "name": "Puma Shorts",
    "slug": "puma-shorts-35",
    "price": 2067,
    "originalPrice": 3900,
    "discount_price": 2067,
    "discount": 47,
    "discountPercentage": 47,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Puma",
    "color": "Yellow",
    "fabric": "Leather",
    "type": "Shorts",
    "pattern": "Plaid",
    "fit": "Oversized",
    "occasion": "Casual",
    "collar": null,
    "rating": 4.6,
    "review_count": 106,
    "images": [
      "/images/men/clothing/shorts/shorts3.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts3.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 3,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_35",
    "name": "Raymond Shorts",
    "slug": "raymond-shorts-36",
    "price": 1034,
    "originalPrice": 1310,
    "discount_price": 1034,
    "discount": 21,
    "discountPercentage": 21,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Raymond",
    "color": "Black",
    "fabric": "Crepe",
    "type": "Shorts",
    "pattern": "Striped",
    "fit": "Oversized",
    "occasion": "Vacation",
    "collar": null,
    "rating": 4.6,
    "review_count": 99,
    "images": [
      "/images/men/clothing/shorts/shorts4.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts4.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 5,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_36",
    "name": "Allen Solly Shorts",
    "slug": "allen-solly-shorts-37",
    "price": 3583,
    "originalPrice": 4370,
    "discount_price": 3583,
    "discount": 18,
    "discountPercentage": 18,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Allen Solly",
    "color": "Teal",
    "fabric": "Wool",
    "type": "Shorts",
    "pattern": "Striped",
    "fit": "Relaxed Fit",
    "occasion": "Vacation",
    "collar": null,
    "rating": 3.9,
    "review_count": 254,
    "images": [
      "/images/men/clothing/shorts/shorts5.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts5.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38"
    ],
    "size": "28",
    "stock": 5,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_37",
    "name": "Puma Shorts",
    "slug": "puma-shorts-38",
    "price": 1113,
    "originalPrice": 2100,
    "discount_price": 1113,
    "discount": 47,
    "discountPercentage": 47,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Puma",
    "color": "Pink",
    "fabric": "Crepe",
    "type": "Shorts",
    "pattern": "Striped",
    "fit": "Tailored Fit",
    "occasion": "Festive",
    "collar": null,
    "rating": 4.7,
    "review_count": 313,
    "images": [
      "/images/men/clothing/shorts/shorts6.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts6.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 2,
    "isLimitedStock": true,
    "featured": true,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_38",
    "name": "W for Woman Shorts",
    "slug": "w-for woman-shorts-39",
    "price": 1927,
    "originalPrice": 2640,
    "discount_price": 1927,
    "discount": 27,
    "discountPercentage": 27,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "W for Woman",
    "color": "Navy",
    "fabric": "Silk",
    "type": "Shorts",
    "pattern": "Checked",
    "fit": "Slim Fit",
    "occasion": "Wedding",
    "collar": null,
    "rating": 4.9,
    "review_count": 206,
    "images": [
      "/images/men/clothing/shorts/shorts7.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts7.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36"
    ],
    "size": "28",
    "stock": 14,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_39",
    "name": "Allen Solly Shorts",
    "slug": "allen-solly-shorts-40",
    "price": 1074,
    "originalPrice": 1360,
    "discount_price": 1074,
    "discount": 21,
    "discountPercentage": 21,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Allen Solly",
    "color": "Yellow",
    "fabric": "Linen",
    "type": "Shorts",
    "pattern": "Polka Dots",
    "fit": "Regular Fit",
    "occasion": "Party",
    "collar": null,
    "rating": 4.9,
    "review_count": 450,
    "images": [
      "/images/men/clothing/shorts/shorts8.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts8.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38"
    ],
    "size": "28",
    "stock": 5,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_40",
    "name": "Raymond Shorts",
    "slug": "raymond-shorts-41",
    "price": 964,
    "originalPrice": 1440,
    "discount_price": 964,
    "discount": 33,
    "discountPercentage": 33,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Raymond",
    "color": "Black",
    "fabric": "Satin",
    "type": "Shorts",
    "pattern": "Checked",
    "fit": "Oversized",
    "occasion": "Work",
    "collar": null,
    "rating": 4.7,
    "review_count": 112,
    "images": [
      "/images/men/clothing/shorts/shorts9.webp"
    ],
    "image": "/images/men/clothing/shorts/shorts9.webp",
    "description": "A premium shorts designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38"
    ],
    "size": "28",
    "stock": 3,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_41",
    "name": "W for Woman Track Pants",
    "slug": "w-for woman-track-pants-42",
    "price": 1764,
    "originalPrice": 3330,
    "discount_price": 1764,
    "discount": 47,
    "discountPercentage": 47,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "W for Woman",
    "color": "Olive",
    "fabric": "Polyester",
    "type": "Track Pants",
    "pattern": "Embroidered",
    "fit": "Oversized",
    "occasion": "Formal",
    "collar": null,
    "rating": 4.6,
    "review_count": 137,
    "images": [
      "/images/men/clothing/track-pants/tpants1.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants1.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 5,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_42",
    "name": "Levis Track Pants",
    "slug": "levis-track-pants-43",
    "price": 4287,
    "originalPrice": 4420,
    "discount_price": 4287,
    "discount": 3,
    "discountPercentage": 3,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Levis",
    "color": "Grey",
    "fabric": "Georgette",
    "type": "Track Pants",
    "pattern": "Embroidered",
    "fit": "Slim Fit",
    "occasion": "Festive",
    "collar": null,
    "rating": 3.9,
    "review_count": 378,
    "images": [
      "/images/men/clothing/track-pants/tpants10.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants10.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38"
    ],
    "size": "28",
    "stock": 1,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_43",
    "name": "Allen Solly Track Pants",
    "slug": "allen-solly-track-pants-44",
    "price": 3304,
    "originalPrice": 4030,
    "discount_price": 3304,
    "discount": 18,
    "discountPercentage": 18,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Allen Solly",
    "color": "Brown",
    "fabric": "Velvet",
    "type": "Track Pants",
    "pattern": "Polka Dots",
    "fit": "Slim Fit",
    "occasion": "Lounge",
    "collar": null,
    "rating": 4.1,
    "review_count": 303,
    "images": [
      "/images/men/clothing/track-pants/tpants2.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants2.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36"
    ],
    "size": "28",
    "stock": 11,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_44",
    "name": "Levis Track Pants",
    "slug": "levis-track-pants-45",
    "price": 563,
    "originalPrice": 640,
    "discount_price": 563,
    "discount": 12,
    "discountPercentage": 12,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Levis",
    "color": "Yellow",
    "fabric": "Cotton",
    "type": "Track Pants",
    "pattern": "Checked",
    "fit": "Regular Fit",
    "occasion": "Vacation",
    "collar": null,
    "rating": 3.8,
    "review_count": 351,
    "images": [
      "/images/men/clothing/track-pants/tpants3.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants3.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36"
    ],
    "size": "28",
    "stock": 15,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_45",
    "name": "W for Woman Track Pants",
    "slug": "w-for woman-track-pants-46",
    "price": 1803,
    "originalPrice": 2470,
    "discount_price": 1803,
    "discount": 27,
    "discountPercentage": 27,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "W for Woman",
    "color": "Green",
    "fabric": "Cotton",
    "type": "Track Pants",
    "pattern": "Embroidered",
    "fit": "Oversized",
    "occasion": "Work",
    "collar": null,
    "rating": 4.4,
    "review_count": 298,
    "images": [
      "/images/men/clothing/track-pants/tpants4.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants4.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 4,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_46",
    "name": "Nike Track Pants",
    "slug": "nike-track-pants-47",
    "price": 2988,
    "originalPrice": 4820,
    "discount_price": 2988,
    "discount": 38,
    "discountPercentage": 38,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Nike",
    "color": "Brown",
    "fabric": "Wool",
    "type": "Track Pants",
    "pattern": "Plaid",
    "fit": "Tailored Fit",
    "occasion": "Party",
    "collar": null,
    "rating": 5,
    "review_count": 16,
    "images": [
      "/images/men/clothing/track-pants/tpants5.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants5.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36"
    ],
    "size": "28",
    "stock": 1,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_47",
    "name": "Levis Track Pants",
    "slug": "levis-track-pants-48",
    "price": 2415,
    "originalPrice": 2490,
    "discount_price": 2415,
    "discount": 3,
    "discountPercentage": 3,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Levis",
    "color": "Maroon",
    "fabric": "Nylon",
    "type": "Track Pants",
    "pattern": "Embroidered",
    "fit": "Skinny Fit",
    "occasion": "Festive",
    "collar": null,
    "rating": 4.8,
    "review_count": 44,
    "images": [
      "/images/men/clothing/track-pants/tpants6.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants6.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 7,
    "isLimitedStock": false,
    "featured": true,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_48",
    "name": "Zara Track Pants",
    "slug": "zara-track-pants-49",
    "price": 3635,
    "originalPrice": 4980,
    "discount_price": 3635,
    "discount": 27,
    "discountPercentage": 27,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Zara",
    "color": "Grey",
    "fabric": "Satin",
    "type": "Track Pants",
    "pattern": "Striped",
    "fit": "Oversized",
    "occasion": "Vacation",
    "collar": null,
    "rating": 4.8,
    "review_count": 438,
    "images": [
      "/images/men/clothing/track-pants/tpants7.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants7.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32"
    ],
    "size": "28",
    "stock": 9,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_49",
    "name": "Allen Solly Track Pants",
    "slug": "allen-solly-track-pants-50",
    "price": 4422,
    "originalPrice": 4860,
    "discount_price": 4422,
    "discount": 9,
    "discountPercentage": 9,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Allen Solly",
    "color": "Blue",
    "fabric": "Crepe",
    "type": "Track Pants",
    "pattern": "Abstract",
    "fit": "Tailored Fit",
    "occasion": "Party",
    "collar": null,
    "rating": 3.8,
    "review_count": 329,
    "images": [
      "/images/men/clothing/track-pants/tpants8.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants8.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36"
    ],
    "size": "28",
    "stock": 5,
    "isLimitedStock": true,
    "featured": true,
    "bestseller": false,
    "new_arrival": true
  },
  {
    "id": "local_p_50",
    "name": "Levis Track Pants",
    "slug": "levis-track-pants-51",
    "price": 1339,
    "originalPrice": 1810,
    "discount_price": 1339,
    "discount": 26,
    "discountPercentage": 26,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Levis",
    "color": "Olive",
    "fabric": "Crepe",
    "type": "Track Pants",
    "pattern": "Solid",
    "fit": "Oversized",
    "occasion": "Work",
    "collar": null,
    "rating": 4.3,
    "review_count": 313,
    "images": [
      "/images/men/clothing/track-pants/tpants9.webp"
    ],
    "image": "/images/men/clothing/track-pants/tpants9.webp",
    "description": "A premium track pants designed for style and comfort.",
    "sizes": [
      "28",
      "30",
      "32",
      "34",
      "36",
      "38",
      "40"
    ],
    "size": "28",
    "stock": 4,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_51",
    "name": "H&M Tshirts",
    "slug": "h&m-tshirts-52",
    "price": 586,
    "originalPrice": 850,
    "discount_price": 586,
    "discount": 31,
    "discountPercentage": 31,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "H&M",
    "color": "Navy",
    "fabric": "Velvet",
    "type": "Tshirts",
    "pattern": "Solid",
    "fit": "Loose Fit",
    "occasion": "Work",
    "collar": "Spread",
    "rating": 4.4,
    "review_count": 58,
    "images": [
      "/images/men/clothing/tshirts/tshirts1.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts1.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "size": "XS",
    "stock": 13,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_52",
    "name": "Zara Tshirts",
    "slug": "zara-tshirts-53",
    "price": 595,
    "originalPrice": 1190,
    "discount_price": 595,
    "discount": 50,
    "discountPercentage": 50,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Zara",
    "color": "Green",
    "fabric": "Georgette",
    "type": "Tshirts",
    "pattern": "Abstract",
    "fit": "Loose Fit",
    "occasion": "Casual",
    "collar": "Button-Down",
    "rating": 4.3,
    "review_count": 433,
    "images": [
      "/images/men/clothing/tshirts/tshirts10.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts10.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "size": "XS",
    "stock": 11,
    "isLimitedStock": false,
    "featured": true,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_53",
    "name": "H&M Tshirts",
    "slug": "h&m-tshirts-54",
    "price": 2380,
    "originalPrice": 3500,
    "discount_price": 2380,
    "discount": 32,
    "discountPercentage": 32,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "H&M",
    "color": "White",
    "fabric": "Cotton",
    "type": "Tshirts",
    "pattern": "Printed",
    "fit": "Tailored Fit",
    "occasion": "Party",
    "collar": "Turtleneck",
    "rating": 3.9,
    "review_count": 439,
    "images": [
      "/images/men/clothing/tshirts/tshirts2.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts2.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "size": "XS",
    "stock": 5,
    "isLimitedStock": true,
    "featured": false,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_54",
    "name": "Puma Tshirts",
    "slug": "puma-tshirts-55",
    "price": 2287,
    "originalPrice": 2460,
    "discount_price": 2287,
    "discount": 7,
    "discountPercentage": 7,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Puma",
    "color": "Brown",
    "fabric": "Cotton",
    "type": "Tshirts",
    "pattern": "Polka Dots",
    "fit": "Relaxed Fit",
    "occasion": "Festive",
    "collar": "Button-Down",
    "rating": 4.5,
    "review_count": 370,
    "images": [
      "/images/men/clothing/tshirts/tshirts3.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts3.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M"
    ],
    "size": "XS",
    "stock": 11,
    "isLimitedStock": false,
    "featured": true,
    "bestseller": true,
    "new_arrival": false
  },
  {
    "id": "local_p_55",
    "name": "H&M Tshirts",
    "slug": "h&m-tshirts-56",
    "price": 2060,
    "originalPrice": 3680,
    "discount_price": 2060,
    "discount": 44,
    "discountPercentage": 44,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "H&M",
    "color": "Olive",
    "fabric": "Velvet",
    "type": "Tshirts",
    "pattern": "Printed",
    "fit": "Tailored Fit",
    "occasion": "Casual",
    "collar": "Boat Neck",
    "rating": 4.9,
    "review_count": 186,
    "images": [
      "/images/men/clothing/tshirts/tshirts4.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts4.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M"
    ],
    "size": "XS",
    "stock": 4,
    "isLimitedStock": true,
    "featured": true,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_56",
    "name": "H&M Tshirts",
    "slug": "h&m-tshirts-57",
    "price": 1600,
    "originalPrice": 3020,
    "discount_price": 1600,
    "discount": 47,
    "discountPercentage": 47,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "H&M",
    "color": "Green",
    "fabric": "Chiffon",
    "type": "Tshirts",
    "pattern": "Printed",
    "fit": "Loose Fit",
    "occasion": "Lounge",
    "collar": "Spread",
    "rating": 3.8,
    "review_count": 229,
    "images": [
      "/images/men/clothing/tshirts/tshirts5.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts5.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL"
    ],
    "size": "XS",
    "stock": 7,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_57",
    "name": "Zara Tshirts",
    "slug": "zara-tshirts-58",
    "price": 579,
    "originalPrice": 840,
    "discount_price": 579,
    "discount": 31,
    "discountPercentage": 31,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Zara",
    "color": "Black",
    "fabric": "Nylon",
    "type": "Tshirts",
    "pattern": "Striped",
    "fit": "Loose Fit",
    "occasion": "Vacation",
    "collar": "Boat Neck",
    "rating": 3.8,
    "review_count": 389,
    "images": [
      "/images/men/clothing/tshirts/tshirts6.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts6.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "size": "XS",
    "stock": 9,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": true
  },
  {
    "id": "local_p_58",
    "name": "H&M Tshirts",
    "slug": "h&m-tshirts-59",
    "price": 563,
    "originalPrice": 640,
    "discount_price": 563,
    "discount": 12,
    "discountPercentage": 12,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "H&M",
    "color": "Green",
    "fabric": "Crepe",
    "type": "Tshirts",
    "pattern": "Floral",
    "fit": "Regular Fit",
    "occasion": "Festive",
    "collar": "Henley",
    "rating": 3.5,
    "review_count": 221,
    "images": [
      "/images/men/clothing/tshirts/tshirts7.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts7.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M",
      "L",
      "XL",
      "XXL",
      "3XL"
    ],
    "size": "XS",
    "stock": 3,
    "isLimitedStock": true,
    "featured": true,
    "bestseller": false,
    "new_arrival": false
  },
  {
    "id": "local_p_59",
    "name": "Raymond Tshirts",
    "slug": "raymond-tshirts-60",
    "price": 3146,
    "originalPrice": 4840,
    "discount_price": 3146,
    "discount": 35,
    "discountPercentage": 35,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Raymond",
    "color": "White",
    "fabric": "Georgette",
    "type": "Tshirts",
    "pattern": "Striped",
    "fit": "Tailored Fit",
    "occasion": "Formal",
    "collar": "V-Neck",
    "rating": 4.2,
    "review_count": 101,
    "images": [
      "/images/men/clothing/tshirts/tshirts8.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts8.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M"
    ],
    "size": "XS",
    "stock": 1,
    "isLimitedStock": true,
    "featured": true,
    "bestseller": false,
    "new_arrival": true
  },
  {
    "id": "local_p_60",
    "name": "Raymond Tshirts",
    "slug": "raymond-tshirts-61",
    "price": 362,
    "originalPrice": 510,
    "discount_price": 362,
    "discount": 29,
    "discountPercentage": 29,
    "category": "Men",
    "subcategory": "Clothing",
    "brand": "Raymond",
    "color": "Yellow",
    "fabric": "Linen",
    "type": "Tshirts",
    "pattern": "Printed",
    "fit": "Loose Fit",
    "occasion": "Wedding",
    "collar": "Spread",
    "rating": 4.9,
    "review_count": 376,
    "images": [
      "/images/men/clothing/tshirts/tshirts9.webp"
    ],
    "image": "/images/men/clothing/tshirts/tshirts9.webp",
    "description": "A premium tshirts designed for style and comfort.",
    "sizes": [
      "XS",
      "S",
      "M"
    ],
    "size": "XS",
    "stock": 10,
    "isLimitedStock": false,
    "featured": false,
    "bestseller": false,
    "new_arrival": false
  }
];
